apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vote-ui
spec:
  params:
  - default: pipelines-vote-ui
    name: APP_NAME
    type: string
  - default: https://github.com/blues-man/pipelines-vote-ui.git
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: quay.io/bluesman/vote-ui
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: 'https://github.com/blues-man/vote-app-gitops.git'
    name: CONFIG_GIT_REPO
    type: string
  - default: develop
    name: CONFIG_GIT_REVISION
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-and-push
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: git-update-deployment
    params:
    - name: GIT_REPOSITORY
      value: $(params.CONFIG_GIT_REPO)
    - name: CURRENT_IMAGE
      value: $(params.IMAGE_NAME)
    - name: NEW_IMAGE
      value: $(params.IMAGE_NAME)
    - name: NEW_DIGEST
      value: $(tasks.build-and-push.results.IMAGE_DIGEST)
    - name: KUSTOMIZATION_PATH
      value: environments/dev
    - name: GIT_REF
      value: $(params.CONFIG_GIT_REVISION)
    runAfter:
      - build-and-push
    taskRef:
      kind: Task
      name: git-update-deployment
    workspaces:
    - name: workspace
      workspace: workspace
  workspaces:
  - name: workspace
